exports.LISTA_PRODUTOS = 'SELECT ID AS id, NOME AS nome FROM PRODUTO ORDER BY ID;';
exports.LISTA_TRAZAS_PROD = 'SELECT ID AS id, NUMERO AS numero, NOME AS nome FROM FORMA_TRAZA WHERE PRODUTO_ID = ? ORDER BY NUMERO;';
exports.COMPROBAR_TOKEN = 'SELECT ACTIVO AS activo FROM TOKENS WHERE TOKEN = ?';
exports.ADD_TRAZA = 'INSERT INTO TRAZA (REFERENCIA, TRAZA_ID, DATA, LOCALIZACION, LATITUD, LONGITUD) VALUE (?, ?, ?, ?, ?, ?);';
exports.TRAZA_DE_REF = `SELECT
COUNT(*) AS existe
FROM FORMA_TRAZA F
WHERE F.PRODUTO_ID = (SELECT P.PRODUTO_ID FROM PRODUTO_REF P WHERE P.REFERENCIA = ?) AND F.ID = ?;`;