version: '2'
services:
  m-backend:
    image: backend
    depends_on:
      - m-mysql
    restart: always
    ports:
      - "8010:8010"
    networks:
      - milleiro
    environment:
      - PORT=8010
      - MYSQL_HOST=m-mysql
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=milleiro
  m-backend-manage:
    image: backend-manage
    depends_on:
      - m-mysql
    restart: always
    ports:
      - "8020:8020"
    networks:
      - milleiro
    environment:
      - PORT=8020
      - MYSQL_HOST=m-mysql
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=milleiro
      - WEB_PASSWORD=password
  m-backend-add-app:
    image: backend-add-app
    depends_on:
      - m-mysql
    restart: always
    ports:
      - "8030:8030"
    networks:
      - milleiro
    environment:
      - PORT=8030
      - MYSQL_HOST=m-mysql
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=milleiro
  m-milleiroapp-backend:
    image: milleiroapp-backend
    depends_on:
      - m-mysql
    restart: always
    ports:
      - "8040:8040"
    networks:
      - milleiro
    environment:
      - PORT=8040
      - MYSQL_HOST=m-mysql
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=milleiro
  m-mysql:
    image: milleiro-sql
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - milleiro
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  milleiro:
    driver: bridge
